name: deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency: deploy-production

jobs:
  login:
    name: Azure Container Apps
    runs-on: [self-hosted, linux, x64] # running on my vps
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


  image:
    name: production image
    runs-on: [self-hosted, linux, x64]
    needs: [login]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Build front image
        run: docker build -t resolveai-front:${{ github.sha }} .

  deploy:
    name: Azure Container Apps
    runs-on: [self-hosted, linux, x64] # running on my vps
    needs: [image]
    if: startsWith(github.ref, 'refs/tags/v')
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ACR Tasks (az acr build) isn't allowed on this subscription
      # I am buiding in my vps and pushing the image to azure
      - name: Build and push the front image
        run: |
          az acr login -n "${{ vars.ACR_NAME }}"
          image="${{ vars.ACR_NAME }}.azurecr.io/resolveai-front"
          docker build -t "$image:${{ github.sha }}" -t "$image:latest" .
          docker push "$image:${{ github.sha }}"
          docker push "$image:latest"

      - name: Roll out a new revision
        run: |
          az containerapp update \
            -g "${{ vars.RESOURCE_GROUP }}" -n resolveai-front \
            --image "${{ vars.ACR_NAME }}.azurecr.io/resolveai-front:${{ github.sha }}"
